Repository doerffler/accounting-control-center, pull requests merged in 2022-09, with the labels that each got.

#64 Add license to the repository
  LICENSE.md
  README.md
Labels: documentation

#63 61 enhance the datamodel with a connection between geschäftsjahr and auftrag
  DoePaAdminApp/Views/MainWindow.xaml
  DoePaAdminApp/Views/ManageAuftraegeWindow.xaml
  DoePaAdminDataModel/DoePaKlassendiagramm.cd
  DoePaAdminDataModel/Stammdaten/Auftrag.cs
  DoePaAdminDataModel/Stammdaten/Geschaeftsjahr.cs
  DoePaAdminViewModel/ManageAuftraegeViewModel.cs
  DoePaAdminViewModel/Services/DoePaAdminTestDataCreator.cs
Labels: enhancement

#65 Merge recent changes to update readme an license
  DoePaAdminApp/Views/MainWindow.xaml
  DoePaAdminApp/Views/ManageAuftraegeWindow.xaml
  DoePaAdminDataModel/DoePaKlassendiagramm.cd
  DoePaAdminDataModel/Stammdaten/Auftrag.cs
  DoePaAdminDataModel/Stammdaten/Geschaeftsjahr.cs
  DoePaAdminViewModel/ManageAuftraegeViewModel.cs
  DoePaAdminViewModel/Services/DoePaAdminTestDataCreator.cs
  LICENSE.md
  README.md
Labels: documentation, enhancement
